version: "3"
services:
    dashboard:
        build: .
        hostname: groove
        command: /startserver
        env_file: ./.env
        ports:
            - 8000:5085
        volumes:
            - ./:/PROJECT/