#!/bin/bash


echo "CHECKING ALL SERVICE!!!"
sleep 1s

set -o errexit
set -o nounset

###########################################################
#### INSTALLING THE CUSTOM 404 PAGE FOR DEBUG ####
/custom404
################# MYSQL CONFIGURATIONS ####################
cd /PROJECT

# python manage.py collectstatic --noinput

python manage.py runserver 0.0.0.0:5085
###########################################################
